### ISSUE TITLE
[enjoy] Press F12 to be a genius :D

### ISSUE THREAD

**Issue by GeeSuth** [erinnmclaughlin/Wordlp#3]
Hey! 
I like the game and I like the coding here! 
the solution can find in a local storage for browser 

![image](https://user-images.githubusercontent.com/10328974/190859534-dbdcee7d-b90f-4027-ac73-007ee67f55fb.png)

have a great day

**Comment by erinnmclaughlin** [comment]
Hey! Yeah, that's a problem I'm aware of but have chosen to ignore for now (target audience = a small group of not-very-tech-savvy people playing on their phones lol)
